/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/OneRoomApartment.glb
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import gsap from "gsap";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

export function OneRoomApartment(props) {
  const { nodes, materials } = useGLTF("./Models/OneRoomApartment.glb");
  const canvas1 = materials.Canvas_1;
  //stop flickering for texture in canvas1
  canvas1.map.magFilter = THREE.NearestFilter;
  canvas1.map.minFilter = THREE.LinearFilter;
  canvas1.map.wrapS = THREE.RepeatWrapping;
  canvas1.map.wrapT = THREE.RepeatWrapping;
  canvas1.map.repeat.set(1, 1);

  const ref = useRef();
  const tl = useRef();

  //use gsap to animate the position of the model
  useFrame(() => {
    if (tl.current) {
      tl.current.progress();
    }
  });

  //use gsap to animate the position of the model one time
  React.useEffect(() => {
    tl.current = gsap.timeline({ repeat: 0, yoyo: false });
    tl.current.to(ref.current.position, {
      duration: 5,
      x: 0,
      y: 0,
      z: 0,
      ease: "power1.inOut",
    });
  }, []);

  return (
    <group
      {...props}
      dispose={null}
      scale={[25, 25, 25]}
      ref={ref}
      position={[0, -400, 0]}
    >
      <mesh
        geometry={nodes.AI37_008_lamp_002_11_Lamp_floor_0.geometry}
        material={materials.Lamp_floor}
      />
      <mesh
        geometry={nodes.Apples_Apples_0.geometry}
        material={materials.Apples}
      />
      <mesh geometry={nodes.Bed_Bed_0.geometry} material={materials.material} />
      <mesh
        geometry={nodes.Brick_Facade001_Facade_0.geometry}
        material={materials.Facade}
      />
      <mesh geometry={nodes.canvas001_Canvas_1_0.geometry} material={canvas1} />
      <mesh
        geometry={nodes.canvas002_Canvas_2_0.geometry}
        material={materials.Canvas_2}
      />
      <mesh
        geometry={nodes["canvas003_Material_#2097631456_0"].geometry}
        material={materials.Material_2097631456}
      />
      <mesh
        geometry={nodes.Carpet_bedroom_Carpet_in_BR_0.geometry}
        material={materials.Carpet_in_BR}
      />
      <mesh
        geometry={nodes["carpet06-01_Carpet_in_LR_0"].geometry}
        material={materials.Carpet_in_LR}
      />
      <mesh
        geometry={nodes.Celling_Celling_0.geometry}
        material={materials.Celling}
      />
      <mesh
        geometry={nodes.cgaxis_models_48_06_03_1_Chair_in_LR_0.geometry}
        material={materials.Chair_in_LR}
      />
      <mesh
        geometry={nodes.Chair_1_Chair_1_0.geometry}
        material={materials.Chair_1}
      />
      <mesh
        geometry={nodes.Chair_2_Chair_2_0.geometry}
        material={materials.Chair_2}
      />
      <mesh
        geometry={nodes.Chair_3_Chair_3_0.geometry}
        material={materials.Chair_3}
      />
      <mesh
        geometry={nodes.Chair_4_Chair_4_0.geometry}
        material={materials.Chair_4}
      />
      <mesh
        geometry={nodes.Comode_bedroom_Comode_0.geometry}
        material={materials.Comode}
      />
      <mesh
        geometry={nodes.Comode_entrance_Comode_in_EH_0.geometry}
        material={materials.Comode_in_EH}
      />
      <mesh
        geometry={nodes.Comode_in_LR_Comode_in_LR_0.geometry}
        material={materials.Comode_in_LR}
      />
      <mesh
        geometry={nodes.Cooking_P_Cooking_P_0.geometry}
        material={materials.Cooking_P}
      />
      <mesh
        geometry={nodes.Couch_Couch_0.geometry}
        material={materials.Couch}
      />
      <mesh
        geometry={nodes.Curtain_in_Living_room_Curtains_LR_0.geometry}
        material={materials.Curtains_LR}
      />
      <mesh
        geometry={nodes.Curtains_bedroom_Curtains_in_BR_0.geometry}
        material={materials.Curtains_in_BR}
      />
      <mesh
        geometry={nodes.Cut_exterior_wall_CUT_Walls_0.geometry}
        material={materials.CUT_Walls}
      />
      <mesh
        geometry={nodes.Domophone_Domophone_0.geometry}
        material={materials.Domophone}
      />
      <mesh
        geometry={nodes.Door_bedroom_Door_in_BR_0.geometry}
        material={materials.Door_in_BR}
      />
      <mesh
        geometry={nodes.duravit_strack_2_Toilet_0.geometry}
        material={materials.Toilet}
      />
      <mesh
        geometry={nodes.Entrance_door_Entrance_door_0.geometry}
        material={materials.Entrance_door}
      />
      <mesh
        geometry={nodes.Exterior_wall_Wall_exterior_0.geometry}
        material={materials.Wall_exterior}
      />
      <mesh
        geometry={nodes.Floor_Wood_Floor_wood_0.geometry}
        material={materials.Floor_wood}
      />
      <mesh
        geometry={nodes["Glass_Glass_-_Clear_Fa_0"].geometry}
        material={materials["Glass_-_Clear_Fa"]}
      />
      <mesh
        geometry={nodes.Kitchen_Kitchen_0.geometry}
        material={materials.Kitchen}
      />
      <mesh
        geometry={nodes.Lamp_thumb_Lmp_002_0.geometry}
        material={materials.Lmp_002}
      />
      <mesh
        geometry={nodes.Lamp_thumb002_Lmp_01_0.geometry}
        material={materials.Lmp_01}
      />
      <mesh
        geometry={nodes.Magazines_Magazine_0.geometry}
        material={materials.Magazine}
      />
      <mesh
        geometry={nodes.Matrass_Matras_0.geometry}
        material={materials.Matras}
      />
      <mesh
        geometry={nodes["Mirror_Material_#2097631487_0"].geometry}
        material={materials.Material_2097631487}
      />
      <mesh
        geometry={nodes.Picture_Picture_in_BR_0.geometry}
        material={materials.Picture_in_BR}
      />
      <mesh
        geometry={nodes.Pillows_on_couch_Pillows_0.geometry}
        material={materials.Pillows}
      />
      <mesh
        geometry={nodes.Pokrivalo_Pokrivalo_0.geometry}
        material={materials.Pokrivalo}
      />
      <mesh
        geometry={nodes.Polotencesuchitel_Polotence_0.geometry}
        material={materials.Polotence}
      />
      <mesh
        geometry={nodes.POT_Pot_0.geometry}
        material={materials.material_55}
      />
      <mesh
        geometry={nodes.Radiator_1_Radiator_1_0.geometry}
        material={materials.Radiator_1}
      />
      <mesh
        geometry={nodes.Radiator_2_Radiator_LR_0.geometry}
        material={materials.Radiator_LR}
      />
      <mesh
        geometry={nodes["Sink_Material_#2097631458_0"].geometry}
        material={materials.Material_2097631458}
      />
      <mesh
        geometry={nodes.Sink_mirror_mirror_toilet_0.geometry}
        material={materials.mirror_toilet}
      />
      <mesh
        geometry={nodes.Sink_toilet_Toilet_sink_0.geometry}
        material={materials.Toilet_sink}
      />
      <mesh geometry={nodes.Slab_Slab_0.geometry} material={materials.Slab} />
      <mesh
        geometry={nodes.Table_Table_Kitchen_0.geometry}
        material={materials.Table_Kitchen}
      />
      <mesh
        geometry={nodes.Table_in_LR_Coffee_table_0.geometry}
        material={materials.Coffee_table}
      />
      <mesh
        geometry={nodes.AY301SA_008_Tap_AYATI_01_0.geometry}
        material={materials.Tap_AYATI_01}
      />
      <mesh
        geometry={nodes.Tile_floor_Floor_Ceramic_0.geometry}
        material={materials.Floor_Ceramic}
      />
      <mesh
        geometry={nodes.Toilet_door_Toilet_door_0.geometry}
        material={materials.Toilet_door}
      />
      <mesh
        geometry={nodes.TV_1_TV_in_LR_0.geometry}
        material={materials.TV_in_LR}
      />
      <mesh
        geometry={nodes.TV_2_TV_in_LR_0.geometry}
        material={materials.TV_in_LR}
      />
      <mesh
        geometry={nodes.Vanna_Vanna_0.geometry}
        material={materials.Vanna}
      />
      <mesh
        geometry={nodes.Walls_Walls_0.geometry}
        material={materials.Walls}
      />
      <mesh
        geometry={nodes.Warderob_B_Warderobe_0.geometry}
        material={materials.Warderobe}
      />
      <mesh
        geometry={nodes.Warderobe_A_Warderobe_in_EH_0.geometry}
        material={materials.Warderobe_in_EH}
      />
      <mesh
        geometry={nodes.Washing_cupboard_Toilet_cupboard_0.geometry}
        material={materials.Toilet_cupboard}
      />
      <mesh
        geometry={nodes.Window_bedroom_Window_BR_0.geometry}
        material={materials.Window_BR}
      />
      <mesh
        geometry={nodes.Window_in_lr_Window_in_LR_0.geometry}
        material={materials.Window_in_LR}
      />
    </group>
  );
}

useGLTF.preload("/Models//OneRoomApartment.glb");
