/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/Rosalia.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useFrame } from '@react-three/fiber'

export const Rosalia = (props) => {
  const { nodes, materials } = useGLTF('/Models/Rosalia.glb')
  const ref = useRef();
  const tl = useRef();

  //use gsap to animate the position of the model
  useFrame(() => {
    if (tl.current) {
      tl.current.progress();
    }
  });

  //use gsap to animate the position of the model one time
  React.useEffect(() => {
    tl.current = gsap.timeline({ repeat: 0, yoyo: false });
    tl.current.to(ref.current.position, {
      duration: 3,
      x: 0,
      y: 0,
      z: 0,
      ease: "power1.inOut",
    });
  }, []);
  return (
    <group {...props} dispose={null} ref={ref} position={[0, -250, 0]}>
      <group position={[28.94, -1.4, 9.1]}>
        <mesh geometry={nodes.Flagga.geometry} material={materials.Sverige_Flagga} />
        <mesh geometry={nodes.Flaggstang_1.geometry} material={materials.Flaggstang_m_1} />
        <mesh geometry={nodes.Guld.geometry} material={materials.Guld1} />
        <mesh geometry={nodes['Mark_karm_1_(17)'].geometry} material={materials.Karm_ljus} position={[8.94, 4.38, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.07]} />
        <mesh geometry={nodes['Mark_karm_1_(18)'].geometry} material={materials.Karm_ljus} position={[8.94, 7.15, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.07]} />
        <mesh geometry={nodes['Mark_karm_1_(19)'].geometry} material={materials.Karm_ljus} position={[8.94, 9.91, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.07]} />
        <mesh geometry={nodes['Mark_karm_1_(20)'].geometry} material={materials.Karm_ljus} position={[8.94, 12.71, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.07]} />
        <mesh geometry={nodes['Mark_karm_1_(21)'].geometry} material={materials.Karm_ljus} position={[8.94, 15.48, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.07]} />
        <mesh geometry={nodes['Mark_karm_1_(22)'].geometry} material={materials.Karm_ljus} position={[8.94, 18.25, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.09]} />
        <mesh geometry={nodes['Mark_karm_1_(23)'].geometry} material={materials.Karm_ljus} position={[8.94, 21.04, -31.58]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 1191.09]} />
        <mesh geometry={nodes['Mark_karm_1_(24)'].geometry} material={materials.Karm_ljus} position={[8.94, 1.6, -34.84]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 550.46]} />
        <mesh geometry={nodes.Mark_karm_1.geometry} material={materials.Karm_mork} position={[8.94, 15.48, 16.64]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 417.3]} />
        <mesh geometry={nodes['Mark_karm_1_(1)'].geometry} material={materials.Karm_mork} position={[8.94, 12.71, 16.64]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 417.3]} />
        <mesh geometry={nodes['Mark_karm_1_(2)'].geometry} material={materials.Karm_mork} position={[8.94, 9.91, 16.64]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 417.3]} />
        <mesh geometry={nodes['Mark_karm_1_(3)'].geometry} material={materials.Karm_mork} position={[8.94, 7.15, 16.64]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 417.3]} />
        <mesh geometry={nodes['Mark_karm_1_(4)'].geometry} material={materials.Karm_mork} position={[8.94, 4.38, 16.64]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 417.3]} />
        <mesh geometry={nodes['Mark_karm_1_(5)'].geometry} material={materials.Karm_mork} position={[8.94, 1.62, 17.91]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 141.32]} />
        <mesh geometry={nodes['Mark_karm_1_(12)'].geometry} material={materials.Karm_mork} position={[8.94, 15.48, 4.43]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 141.32]} />
        <mesh geometry={nodes['Mark_karm_1_(13)'].geometry} material={materials.Karm_mork} position={[8.94, 12.71, 4.43]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 141.32]} />
        <mesh geometry={nodes['Mark_karm_1_(14)'].geometry} material={materials.Karm_mork} position={[8.94, 9.91, 4.43]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 141.32]} />
        <mesh geometry={nodes['Mark_karm_1_(15)'].geometry} material={materials.Karm_mork} position={[8.94, 7.15, 4.43]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 141.32]} />
        <mesh geometry={nodes['Mark_karm_1_(16)'].geometry} material={materials.Karm_mork} position={[8.94, 4.38, 4.43]} rotation={[0, 0, -Math.PI / 2]} scale={[55.85, 231.93, 141.32]} />
        <mesh geometry={nodes['Mark_karm_1_(2)_1'].geometry} material={materials.Karm_mork} position={[-41.74, 9.91, -38.51]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[55.85, 231.93, 171.68]} />
        <mesh geometry={nodes['Mark_karm_1_(3)_1'].geometry} material={materials.Karm_mork} position={[-41.74, 7.17, -38.51]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[55.85, 231.93, 171.68]} />
        <mesh geometry={nodes['Mark_karm_1_(4)_1'].geometry} material={materials.Karm_mork} position={[-41.74, 4.38, -38.51]} rotation={[-Math.PI / 2, 1.57, 0]} scale={[55.85, 231.93, 171.68]} />
        <mesh geometry={nodes.Armatur.geometry} material={materials.lambert54} />
        <mesh geometry={nodes.Balkonger.geometry} material={materials.Balkong} />
        <mesh geometry={nodes.Botten.geometry} material={materials.Botten_m} />
        <mesh geometry={nodes.Fonster_glas.geometry} material={materials.Fonster_Glas} />
        <mesh geometry={nodes.Golv.geometry} material={materials.Ek_trestav} />
        <mesh geometry={nodes.Innetak.geometry} material={materials.Innetak1} />
        <mesh geometry={nodes.Innevaggar.geometry} material={materials.innerwalls001} />
        <mesh geometry={nodes.Stuprannor.geometry} material={materials.Stupranna} />
        <mesh geometry={nodes.Takdetaljer.geometry} material={materials.Tak_detalj} />
        <mesh geometry={nodes.Vaggar_1.geometry} material={materials.Vit_1} />
        <mesh geometry={nodes.Vaggar_2.geometry} material={materials.innerwalls001} />
        <group position={[-46.17, 0.01, 22.19]} rotation={[0, Math.PI / 2, 0]} scale={1000}>
          <mesh geometry={nodes['Cykel_(3)_2'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(3)_3'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(3)_4'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(3)_5'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(3)_6'].geometry} material={materials['Ram 1']} />
          <mesh geometry={nodes['Cykel_(3)_7'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(3)_8'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-47.63, 0.02, 22.09]} rotation={[2.36, 1.45, -2.35]} scale={1000}>
          <mesh geometry={nodes['Cykel_(4)_2'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(4)_3'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(4)_4'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(4)_5'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(4)_6'].geometry} material={materials['Ram 4']} />
          <mesh geometry={nodes['Cykel_(4)_7'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(4)_8'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-34.03, 0.01, 22.59]} rotation={[0, Math.PI / 2, 0]} scale={1000}>
          <mesh geometry={nodes['Cykel_(5)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(5)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(5)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(5)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(5)_5'].geometry} material={materials['Ram 3']} />
          <mesh geometry={nodes['Cykel_(5)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(5)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-35.49, 0.02, 22.48]} rotation={[2.36, 1.45, -2.35]} scale={1000}>
          <mesh geometry={nodes['Cykel_(6)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(6)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(6)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(6)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(6)_5'].geometry} material={materials['Ram 4']} />
          <mesh geometry={nodes['Cykel_(6)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(6)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-29.82, 0.02, 22.48]} rotation={[2.36, 1.45, -2.35]} scale={1000}>
          <mesh geometry={nodes['Cykel_(7)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(7)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(7)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(7)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(7)_5'].geometry} material={materials['Ram 2']} />
          <mesh geometry={nodes['Cykel_(7)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(7)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-28.36, 0.01, 22.59]} rotation={[0, Math.PI / 2, 0]} scale={1000}>
          <mesh geometry={nodes['Cykel_(8)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(8)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(8)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(8)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(8)_5'].geometry} material={materials.Ram} />
          <mesh geometry={nodes['Cykel_(8)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(8)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-12.67, 0.02, 22.7]} rotation={[2.36, 1.45, -2.35]} scale={1000}>
          <mesh geometry={nodes['Cykel_(9)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(9)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(9)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(9)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(9)_5'].geometry} material={materials['Ram 4']} />
          <mesh geometry={nodes['Cykel_(9)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(9)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-13.82, 0.01, 22.76]} rotation={[0, Math.PI / 2, 0]} scale={1000}>
          <mesh geometry={nodes['Cykel_(10)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(10)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(10)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(10)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(10)_5'].geometry} material={materials['Ram 1']} />
          <mesh geometry={nodes['Cykel_(10)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(10)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[10.34, 0, 8.2]} rotation={[-3.08, 0.18, 3.13]} scale={1000}>
          <mesh geometry={nodes['Cykel_(11)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(11)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(11)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(11)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(11)_5'].geometry} material={materials.Ram} />
          <mesh geometry={nodes['Cykel_(11)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(11)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[10.33, 0, 9.02]} rotation={[-3.08, -0.04, -3.14]} scale={1000}>
          <mesh geometry={nodes['Cykel_(12)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(12)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(12)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(12)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(12)_5'].geometry} material={materials['Ram 3']} />
          <mesh geometry={nodes['Cykel_(12)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(12)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-11.55, 0.76, -39.52]} rotation={[-0.34, -1.39, -0.33]} scale={1000}>
          <mesh geometry={nodes['Cykel_(13)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(13)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(13)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(13)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(13)_5'].geometry} material={materials['Ram 3']} />
          <mesh geometry={nodes['Cykel_(13)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(13)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-12.36, 0.76, -39.43]} rotation={[-2.37, -1.49, -2.37]} scale={1000}>
          <mesh geometry={nodes['Cykel_(14)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(14)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(14)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(14)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(14)_5'].geometry} material={materials['Ram 4']} />
          <mesh geometry={nodes['Cykel_(14)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(14)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-48.68, 0.73, -39.99]} rotation={[-2.37, -1.49, -2.37]} scale={1000}>
          <mesh geometry={nodes['Cykel_(15)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(15)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(15)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(15)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(15)_5'].geometry} material={materials.Ram} />
          <mesh geometry={nodes['Cykel_(15)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(15)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-47.18, 0.73, -40.21]} rotation={[-0.34, -1.39, -0.33]} scale={1000}>
          <mesh geometry={nodes['Cykel_(16)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(16)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(16)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(16)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(16)_5'].geometry} material={materials['Ram 1']} />
          <mesh geometry={nodes['Cykel_(16)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(16)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-47.97, 0.73, -40]} rotation={[-2.86, -1.36, -2.86]} scale={1000}>
          <mesh geometry={nodes['Cykel_(17)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(17)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(17)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(17)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(17)_5'].geometry} material={materials['Ram 2']} />
          <mesh geometry={nodes['Cykel_(17)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(17)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[10.06, 0.57, -9.33]} rotation={[3.06, 0.17, -3.12]} scale={1000}>
          <mesh geometry={nodes['Cykel_(18)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(18)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(18)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(18)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(18)_5'].geometry} material={materials['Ram 2']} />
          <mesh geometry={nodes['Cykel_(18)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(18)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[10.08, 0.58, -10.68]} rotation={[-3.08, 0.18, 3.13]} scale={1000}>
          <mesh geometry={nodes['Cykel_(19)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(19)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(19)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(19)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(19)_5'].geometry} material={materials['Ram 1']} />
          <mesh geometry={nodes['Cykel_(19)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(19)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <mesh geometry={nodes['Cykelstall_frilagt_(1)'].geometry} material={materials.Cykelstall_Vaggar} position={[-25.95, 0.01, 21.42]} rotation={[0, 1.57, 0]} scale={1000} />
        <mesh geometry={nodes['Cykelstall_frilagt_(2)'].geometry} material={materials.Cykelstall_Vaggar} position={[-43.78, 0.01, 21.01]} rotation={[0, 1.57, 0]} scale={1000} />
        <mesh geometry={nodes['Cykelstall_frilagt_(3)'].geometry} material={materials.Cykelstall_Vaggar} position={[-10.25, 0.01, 21.62]} rotation={[0, 1.57, 0]} scale={1000} />
        <mesh geometry={nodes['Cykelstall_frilagt_(4)'].geometry} material={materials.Cykelstall_Vaggar} position={[9.12, 0.01, 5.62]} rotation={[-Math.PI, 0, -Math.PI]} scale={1000} />
        <mesh geometry={nodes['Cykelstall_frilagt_(5)'].geometry} material={materials.Cykelstall_Vaggar} position={[-15.11, 0.72, -38.29]} rotation={[0, -Math.PI / 2, 0]} scale={1000} />
        <mesh geometry={nodes['Cykelstall_frilagt_(6)'].geometry} material={materials.Cykelstall_Vaggar} position={[-51.14, 0.72, -38.98]} rotation={[0, -Math.PI / 2, 0]} scale={1000} />
        <mesh geometry={nodes['Cykelstall_frilagt_(7)'].geometry} material={materials.Cykelstall_Vaggar} position={[8.85, 0.58, -13.36]} rotation={[-Math.PI, 0, -Math.PI]} scale={1000} />
        <mesh geometry={nodes.Fonsterkarm_MeshPart0_1.geometry} material={materials.Fonsterkarm_Mork} />
        <mesh geometry={nodes.Fonsterkarm_MeshPart0_2.geometry} material={materials.Fonsterkarm_Ljus} />
        <mesh geometry={nodes.Fonsterkarm_MeshPart1_1.geometry} material={materials.Fonsterkarm_Ljus} />
        <mesh geometry={nodes.Fonsterkarm_MeshPart1_2.geometry} material={materials.Fonsterkarm_Mork} />
        <mesh geometry={nodes.Fonsterkarm_MeshPart2_1.geometry} material={materials.Fonsterkarm_Ljus} />
        <mesh geometry={nodes.Fonsterkarm_MeshPart2_2.geometry} material={materials.Fonsterkarm_Mork} />
        <mesh geometry={nodes.Balkongracken_1.geometry} material={materials.fence001} />
        <mesh geometry={nodes.Balkongracken_2.geometry} material={materials.Racke} />
        <mesh geometry={nodes.Cykelstall_1.geometry} material={materials.Cykelstall_Vaggar} />
        <mesh geometry={nodes.Cykelstall_2.geometry} material={materials.Cykelstall_vit} />
        <mesh geometry={nodes.Cykelstall_3.geometry} material={materials.Cykelstall_krom} />
        <mesh geometry={nodes.Fasad_1.geometry} material={materials.Tegel_Ljus} />
        <mesh geometry={nodes.Fasad_3.geometry} material={materials.Tegel_Mork} />
        <mesh geometry={nodes.Fasad_4.geometry} material={materials.Fonster_Gra} />
        <mesh geometry={nodes.Fasad_5.geometry} material={materials.Cedertra} />
        <mesh geometry={nodes.Fasad_2_1.geometry} material={materials['Cedertra 1']} />
        <mesh geometry={nodes.Fasad_2_2.geometry} material={materials.Fonster_Svart} />
        <mesh geometry={nodes.Ivy_1_1_1.geometry} material={materials.Ivy2_} />
        <mesh geometry={nodes.Ivy_1_1_2.geometry} material={materials.Ivy1_} />
        <mesh geometry={nodes.Ivy_1_2_1.geometry} material={materials.Ivy2_} />
        <mesh geometry={nodes.Ivy_1_2_2.geometry} material={materials.Ivy1_} />
        <mesh geometry={nodes.Ivy_1_2_3.geometry} material={materials.Ivy3_} />
        <mesh geometry={nodes.Ivy_1_3_1.geometry} material={materials.Ivy2_} />
        <mesh geometry={nodes.Ivy_1_3_2.geometry} material={materials.Ivy1_} />
        <mesh geometry={nodes.Ivy_1_3_3.geometry} material={materials.Ivy3_} />
        <mesh geometry={nodes.Ovrigt_1.geometry} material={materials.Port1} />
        <mesh geometry={nodes.Ovrigt_2.geometry} material={materials.Ivy_hallare} />
        <mesh geometry={nodes.Ovrigt_3.geometry} material={materials.Linje_Svartr} />
        <mesh geometry={nodes.Ovrigt_4.geometry} material={materials['default']} />
        <mesh geometry={nodes.Plank_1.geometry} material={materials.Cedertra_2} />
        <mesh geometry={nodes.Plank_2.geometry} material={materials.Vit_2_reallight} />
        <mesh geometry={nodes.Tak_1.geometry} material={materials.Tak_Gra} />
        <mesh geometry={nodes.Tak_2.geometry} material={materials.Tak_Gra_2} />
        <mesh geometry={nodes.Tak_3.geometry} material={materials.Tak_Sedum} />
        <mesh geometry={nodes.Bankar.geometry} material={materials.TexturesCom_WoodPlanksClean0086_1_seamless_S} />
        <mesh geometry={nodes.Exterior_mark.geometry} material={materials['30003']} />
        <mesh geometry={nodes.Innegard_mark.geometry} material={materials.TexturesCom_AsphaltCloseups0063_1_seamless_S} />
        <group position={[-50.96, 1.49, -17.36]} rotation={[-0.12, 0, 0]} scale={1000}>
          <mesh geometry={nodes.Cykel_1.geometry} material={materials.Sadel} />
          <mesh geometry={nodes.Cykel_2.geometry} material={materials.Crome} />
          <mesh geometry={nodes.Cykel_3.geometry} material={materials.Gears} />
          <mesh geometry={nodes.Cykel_4.geometry} material={materials.Wheels} />
          <mesh geometry={nodes.Cykel_5.geometry} material={materials.Ram} />
          <mesh geometry={nodes.Cykel_6.geometry} material={materials.Stal} />
          <mesh geometry={nodes.Cykel_7.geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-50.96, 1.49, -16.12]} scale={1000}>
          <mesh geometry={nodes['Cykel_(1)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(1)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(1)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(1)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(1)_5'].geometry} material={materials['Ram 1']} />
          <mesh geometry={nodes['Cykel_(1)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(1)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-50.96, 1.49, -11.31]} scale={1000}>
          <mesh geometry={nodes['Cykel_(2)_1'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(2)_2'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(2)_3'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(2)_4'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(2)_5'].geometry} material={materials['Ram 2']} />
          <mesh geometry={nodes['Cykel_(2)_6'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(2)_7'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-50.96, 1.49, -10.15]} rotation={[0, 0.16, 0]} scale={1000}>
          <mesh geometry={nodes['Cykel_(3)_9'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(3)_10'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(3)_11'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(3)_12'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(3)_13'].geometry} material={materials['Ram 3']} />
          <mesh geometry={nodes['Cykel_(3)_14'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(3)_15'].geometry} material={materials.Cykel_Handels} />
        </group>
        <group position={[-50.96, 1.49, -12.3]} rotation={[0, -0.41, 0]} scale={1000}>
          <mesh geometry={nodes['Cykel_(4)_9'].geometry} material={materials.Sadel} />
          <mesh geometry={nodes['Cykel_(4)_10'].geometry} material={materials.Crome} />
          <mesh geometry={nodes['Cykel_(4)_11'].geometry} material={materials.Gears} />
          <mesh geometry={nodes['Cykel_(4)_12'].geometry} material={materials.Wheels} />
          <mesh geometry={nodes['Cykel_(4)_13'].geometry} material={materials['Ram 4']} />
          <mesh geometry={nodes['Cykel_(4)_14'].geometry} material={materials.Stal} />
          <mesh geometry={nodes['Cykel_(4)_15'].geometry} material={materials.Cykel_Handels} />
        </group>
        <mesh geometry={nodes.AM113_062_Tilia5.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia8.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia9.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia10.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia11.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia12.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia13.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia14.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia15.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia16.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia19.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia20.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia21.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia22.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_062_Tilia23.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia24.geometry} material={materials.AM113_062_Tilia_Color_red} />
        <mesh geometry={nodes.AM113_009_Ulmus_1.geometry} material={materials.AM113_009_Ulmus_Bark_Color} />
        <mesh geometry={nodes.AM113_009_Ulmus_2.geometry} material={materials.AM113_009_Ulmus_Color} />
        <mesh geometry={nodes.AM113_009_Ulmus1_1.geometry} material={materials.AM113_009_Ulmus_Bark_Color} />
        <mesh geometry={nodes.AM113_009_Ulmus1_2.geometry} material={materials.AM113_009_Ulmus_Color} />
        <mesh geometry={nodes.AM113_009_Ulmus2_1.geometry} material={materials.AM113_009_Ulmus_Bark_Color} />
        <mesh geometry={nodes.AM113_009_Ulmus2_2.geometry} material={materials.AM113_009_Ulmus_Color} />
        <mesh geometry={nodes.AM113_062_Tilia2_1.geometry} material={materials.AM113_062_Tilia_Bark_Color} />
        <mesh geometry={nodes.AM113_062_Tilia2_2.geometry} material={materials.AM113_062_Tilia_Color_blue} />
        <mesh geometry={nodes.AM113_062_Tilia3_1.geometry} material={materials.AM113_062_Tilia_Bark_Color} />
        <mesh geometry={nodes.AM113_062_Tilia3_2.geometry} material={materials.AM113_062_Tilia_Color_yellow} />
        <mesh geometry={nodes.AM113_062_Tilia4_1.geometry} material={materials.AM113_062_Tilia_Bark_Color} />
        <mesh geometry={nodes.AM113_062_Tilia4_2.geometry} material={materials.AM113_062_Tilia_Color} />
        <mesh geometry={nodes.AM113_062_Tilia6_1.geometry} material={materials.AM113_062_Tilia_Bark_Color} />
        <mesh geometry={nodes.AM113_062_Tilia6_2.geometry} material={materials.AM113_062_Tilia_Color} />
        <mesh geometry={nodes.AM113_062_Tilia7_1.geometry} material={materials.AM113_062_Tilia_Bark_Color} />
        <mesh geometry={nodes.AM113_062_Tilia7_2.geometry} material={materials.AM113_062_Tilia_Color} />
        <mesh geometry={nodes.AM113_062_Tilia18_1.geometry} material={materials.AM113_062_Tilia_Bark_Color} />
        <mesh geometry={nodes.AM113_062_Tilia18_2.geometry} material={materials.AM113_062_Tilia_Color} />
        <mesh geometry={nodes.Omgivning_1.geometry} material={materials.Lekplats_orange} />
        <mesh geometry={nodes.Omgivning_2.geometry} material={materials.Lekplats_gron} />
        <mesh geometry={nodes.Omgivning_3.geometry} material={materials.concrete} />
        <mesh geometry={nodes.Omgivning_4.geometry} material={materials.TexturesCom_Grass0026_1_seamless_S} />
        <mesh geometry={nodes.Omgivning_5.geometry} material={materials.Lekplats_turquis} />
        <mesh geometry={nodes.Omgivning_6.geometry} material={materials.Utemobler} />
        <mesh geometry={nodes.Omgivning_7.geometry} material={materials.Lekplats_rod} />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Rosalia.glb')
